### PR TITLE
[Feature/GUI] Added hud and gui elements (gold, book, tool)

### PR DESCRIPTION
**Pull request by kida31**
Added hud elements for
- "OpenBook Button"
- Gold (and other resources) HUD
- Toolbelt/Toolbar

Gold HUD
Book Button
UqI4dFYGYm

Other changes:
- Added label default for theme

### CODE REVIEW

**Comment by lavenderaddict** [comment]
wow cool visuals @kida31 @Sui-nyan

**Review by Sui-nyan — CHANGES_REQUESTED** [review]
When I start the scene, the tool indicator is not correct. It is correct after i swapped once.
The book is open by default. Please close.

I also think an indicator stating what button to press to switch between tools would be nice.

**Comment by kida31** [comment]
> When I start the scene, the tool indicator is not correct. It is correct after i swapped once. image
> 
> The book is open by default. Please close.
> 
> I also think an indicator stating what button to press to switch between tools would be nice. Similar to the book.

#121 Bug is not solved.

Added common button indicators
Book is closed by default now

**Review by Sui-nyan — APPROVED** [review]
LGTM

**Pull request merged**
